name: "opencv-projects"

services:
  jupyter:
    image: "opencv-projects:latest"
    build:
      context: "./infra/image"
      dockerfile: "./jupyter/Containerfile"
    container_name: "opencv-projects"
    user: "root"
    environment:
      NB_USER: "opencv"
      CHOWN_HOME: "yes"
      TERM: "linux"
    working_dir: "/home/opencv"
    ports:
      - "8888:8888"
    volumes:
      - "./infra/image/jupyter/settings:/opt/conda/share/jupyter/lab/settings"
      - "./infra/image/jupyter/scripts:/home/opencv/scripts"
      - "./src:/home/opencv/workdir"
    # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/running.html#example-2
    command: >-2
      start-notebook.py
      --ServerApp.root_dir=/home/opencv/workdir
      --IdentityProvider.token='opencv'
    # TODO: also add jupyter lab configuration file
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - "compute"
                - "utility"
              driver: "nvidia"
              count: "all"
