name: "opencv-projects"

services:
  jupyter:
    image: "opencv-projects:latest"
    build:
      context: "./infra/image"
      dockerfile: "./jupyter/Containerfile"
    container_name: "opencv-projects"
    user: "root"
    environment:
      NB_USER: "opencv"
      CHOWN_HOME: "yes"
    working_dir: "/home/opencv/workdir"
    ports:
      - "8888:8888"
    volumes:
      - "./infra/image/jupyter/scripts:/home/opencv/scripts"
      - "./src:/home/opencv/workdir/src"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - "nvidia-compute"
                - "utility"
              driver: "nvidia"
              count: "all"
