[tool.jupytext]
formats = "ipynb,py:percent"

[tool.pylsp-mypy]
enabled = true
dmypy = true
# live_mode true is not supported with dmypy = true
live_mode = false
strict = true

# TODO: add more configuration
[tool.mypy]
python_version = "3.11"
warn_return_any = true
plugins = [
  "numpy.typing.mypy_plugin",
]

[tool.ruff]
target-version = "py311"
line-length = 120
indent-width = 2

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []
# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
  # These rules can conflict with formatter, so they should be fixed manually
  "COM812", # Adds trailing comma
  "ISC001", # Concatenates multiple consecutive strings into one

  "D211", # No blank lines before class
  "D213", # Multi line summary second line
  "INP001", # Missing __init__.py
  "D100", # Missing docstring in public module
  "T201", # print statements
  "T203", # pprint statements
  "ERA001", # Commented-out code
  "D101", # Allow public classes without docstrings
  "D103", # Allow public functions without docstrings
  "RET505", # Allow to have else after return for a more functional style
  "TRY002", # No need to create own exception classes
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
